.PHONY: clean

all: titles

titles:
	xelatex title_tabloid_violin.tex
	xelatex title_tabloid_viola_cello.tex
	xelatex title_tabloid_score.tex

clean:
	- rm title_tabloid_violin.pdf
	- rm title_tabloid_viola_cello.pdf
	- rm title_tabloid_score.pdf
